### ISSUE TITLE
Checkpoint OneDrive Link Expired

### ISSUE THREAD

**Issue by cyh03223** [Guliisgreat/VDPG#1]
Can not eval anything without downloading this

**Comment by chi-chi-zx** [comment]
Hi,

The link has been updated, can you please try again?

**Comment by cyh03223** [comment]
Thanks!

Also the pip install yml doesn’t work at all. Do you have the txt file or
how did you set up your env?

Yours sincerely,
Alex

chi-chi-zx ***@***.***>于2024年11月6日 周三00:55写道：

**Comment by chi-chi-zx** [comment]
Can you try to create a conda env by:
conda env create -f torch21_cu118_py39.yml

**Comment by cyh03223** [comment]
Yes, I did for the entire day but I have to say the
torch21_cu118_py39.yml file are too lengthy so solving environment cost
lots of time and there are too many conflicts. I am thinking install them
manually.

If you know much better way, please tell me.

chi-chi-zx ***@***.***>于2024年11月6日 周三01:05写道：

**Comment by cyh03223** [comment]
Hi there, finally could verify your result, please do this to set up base env but not pip install: https://stackoverflow.com/questions/72824468/pip-installing-environment-yml-as-if-its-a-requirements-txt

**Comment by Yxt1212** [comment]
> Hi,
> 
> The link has been updated, can you please try again?

Link expired. Can you update the download link of checkpoint again?

**Comment by chi-chi-zx** [comment]
> > Hi,
> > The link has been updated, can you please try again?
> 
> Link expired. Can you update the download link of checkpoint again?

Hi, the link has been updated. Thanks.
